import React from 'react';
import { Search, Filter } from 'lucide-react';

const Produtos = () => {
  // Lista de todas as imagens da galeria com seus preços extraídos dos nomes dos arquivos
  const products = [
    { image: '/lovable-uploads/galeria/5L - R$27,90  2L - R$12,90.jpeg', price: '5L - R$27,90 / 2L - R$12,90' },
    { image: '/lovable-uploads/galeria/R$    13,90.jpeg', price: 'R$ 13,90' },
    { image: '/lovable-uploads/galeria/R$    16,90 .jpeg', price: 'R$ 16,90' },
    { image: '/lovable-uploads/galeria/R$    17,90  .jpeg', price: 'R$ 17,90' },
    { image: '/lovable-uploads/galeria/R$   13,90 .jpeg', price: 'R$ 13,90' },
    { image: '/lovable-uploads/galeria/R$   13,90.jpeg', price: 'R$ 13,90' },
    { image: '/lovable-uploads/galeria/R$   15,90.jpeg', price: 'R$ 15,90' },
    { image: '/lovable-uploads/galeria/R$  10,50.jpeg', price: 'R$ 10,50' },
    { image: '/lovable-uploads/galeria/R$  13,50.jpeg', price: 'R$ 13,50' },
    { image: '/lovable-uploads/galeria/R$  13,90    .jpeg', price: 'R$ 13,90' },
    { image: '/lovable-uploads/galeria/R$  13,90  .jpeg', price: 'R$ 13,90' },
    { image: '/lovable-uploads/galeria/R$  13,90 .jpeg', price: 'R$ 13,90' },
    { image: '/lovable-uploads/galeria/R$  13,90.jpeg', price: 'R$ 13,90' },
    { image: '/lovable-uploads/galeria/R$  15,90.jpeg', price: 'R$ 15,90' },
    { image: '/lovable-uploads/galeria/R$  17,90.jpeg', price: 'R$ 17,90' },
    { image: '/lovable-uploads/galeria/R$  19,90.jpeg', price: 'R$ 19,90' },
    { image: '/lovable-uploads/galeria/R$  20,90.jpeg', price: 'R$ 20,90' },
    { image: '/lovable-uploads/galeria/R$  29,90   .jpeg', price: 'R$ 29,90' },
    { image: '/lovable-uploads/galeria/R$  29,90 .png', price: 'R$ 29,90' },
    { image: '/lovable-uploads/galeria/R$  32,90.jpeg', price: 'R$ 32,90' },
    { image: '/lovable-uploads/galeria/R$  39,90.jpeg', price: 'R$ 39,90' },
    { image: '/lovable-uploads/galeria/R$ 10,50 .jpeg', price: 'R$ 10,50' },
    { image: '/lovable-uploads/galeria/R$ 10,50.jpeg', price: 'R$ 10,50' },
    { image: '/lovable-uploads/galeria/R$ 10,90.jpeg', price: 'R$ 10,90' },
    { image: '/lovable-uploads/galeria/R$ 13,50.jpeg', price: 'R$ 13,50' },
    { image: '/lovable-uploads/galeria/R$ 13,90    .jpeg', price: 'R$ 13,90' },
    { image: '/lovable-uploads/galeria/R$ 13,90   .jpeg', price: 'R$ 13,90' },
    { image: '/lovable-uploads/galeria/R$ 13,90  .jpeg', price: 'R$ 13,90' },
    { image: '/lovable-uploads/galeria/R$ 13,90 .jpeg', price: 'R$ 13,90' },
    { image: '/lovable-uploads/galeria/R$ 13,90.jpeg', price: 'R$ 13,90' },
    { image: '/lovable-uploads/galeria/R$ 14,90.jpeg', price: 'R$ 14,90' },
    { image: '/lovable-uploads/galeria/R$ 15,90   .jpeg', price: 'R$ 15,90' },
    { image: '/lovable-uploads/galeria/R$ 15,90  .jpeg', price: 'R$ 15,90' },
    { image: '/lovable-uploads/galeria/R$ 15,90 .jpeg', price: 'R$ 15,90' },
    { image: '/lovable-uploads/galeria/R$ 15,90.jpeg', price: 'R$ 15,90' },
    { image: '/lovable-uploads/galeria/R$ 16,50.jpeg', price: 'R$ 16,50' },
    { image: '/lovable-uploads/galeria/R$ 16,90.jpeg', price: 'R$ 16,90' },
    { image: '/lovable-uploads/galeria/R$ 17,90   .jpeg', price: 'R$ 17,90' },
    { image: '/lovable-uploads/galeria/R$ 17,90  .jpeg', price: 'R$ 17,90' },
    { image: '/lovable-uploads/galeria/R$ 17,90 .jpeg', price: 'R$ 17,90' },
    { image: '/lovable-uploads/galeria/R$ 17,90.jpeg', price: 'R$ 17,90' },
    { image: '/lovable-uploads/galeria/R$ 19,90 .jpeg', price: 'R$ 19,90' },
    { image: '/lovable-uploads/galeria/R$ 19,90.jpeg', price: 'R$ 19,90' },
    { image: '/lovable-uploads/galeria/R$ 19,90.png', price: 'R$ 19,90' },
    { image: '/lovable-uploads/galeria/R$ 20,90.jpeg', price: 'R$ 20,90' },
    { image: '/lovable-uploads/galeria/R$ 21,90.jpeg', price: 'R$ 21,90' },
    { image: '/lovable-uploads/galeria/R$ 22,50.jpeg', price: 'R$ 22,50' },
    { image: '/lovable-uploads/galeria/R$ 23,90.jpeg', price: 'R$ 23,90' },
    { image: '/lovable-uploads/galeria/R$ 24,50.jpeg', price: 'R$ 24,50' },
    { image: '/lovable-uploads/galeria/R$ 26,50.jpeg', price: 'R$ 26,50' },
    { image: '/lovable-uploads/galeria/R$ 29,90.jpeg', price: 'R$ 29,90' },
    { image: '/lovable-uploads/galeria/R$ 3,50.jpeg', price: 'R$ 3,50' },
    { image: '/lovable-uploads/galeria/R$ 32,50.jpeg', price: 'R$ 32,50' },
    { image: '/lovable-uploads/galeria/R$ 5,90.jpeg', price: 'R$ 5,90' },
    { image: '/lovable-uploads/galeria/R$ 6,80.jpeg', price: 'R$ 6,80' },
    { image: '/lovable-uploads/galeria/R$ 7,50.jpeg', price: 'R$ 7,50' },
    { image: '/lovable-uploads/galeria/R$ 9,90.jpeg', price: 'R$ 9,90' },
    { image: '/lovable-uploads/galeria/R$ 9.jpeg', price: 'R$ 9' },
    { image: '/lovable-uploads/galeria/R$10,50  .jpeg', price: 'R$ 10,50' },
    { image: '/lovable-uploads/galeria/R$10,50 .jpeg', price: 'R$ 10,50' },
    { image: '/lovable-uploads/galeria/R$10,50.jpeg', price: 'R$ 10,50' },
    { image: '/lovable-uploads/galeria/R$10,50.png', price: 'R$ 10,50' },
    { image: '/lovable-uploads/galeria/R$10,90 .jpeg', price: 'R$ 10,90' },
    { image: '/lovable-uploads/galeria/R$10,90.jpeg', price: 'R$ 10,90' },
    { image: '/lovable-uploads/galeria/R$11,90.jpeg', price: 'R$ 11,90' },
    { image: '/lovable-uploads/galeria/R$12,90 .jpeg', price: 'R$ 12,90' },
    { image: '/lovable-uploads/galeria/R$12,90.jpeg', price: 'R$ 12,90' },
    { image: '/lovable-uploads/galeria/R$125,50.jpeg', price: 'R$ 125,50' },
    { image: '/lovable-uploads/galeria/R$13,50.jpeg', price: 'R$ 13,50' },
    { image: '/lovable-uploads/galeria/R$13,90    .jpeg', price: 'R$ 13,90' },
    { image: '/lovable-uploads/galeria/R$13,90   .jpeg', price: 'R$ 13,90' },
    { image: '/lovable-uploads/galeria/R$13,90  .jpeg', price: 'R$ 13,90' },
    { image: '/lovable-uploads/galeria/R$13,90 .jpeg', price: 'R$ 13,90' },
    { image: '/lovable-uploads/galeria/R$13,90.jpeg', price: 'R$ 13,90' },
    { image: '/lovable-uploads/galeria/R$14,50.jpeg', price: 'R$ 14,50' },
    { image: '/lovable-uploads/galeria/R$14,50.png', price: 'R$ 14,50' },
    { image: '/lovable-uploads/galeria/R$14,90  .jpeg', price: 'R$ 14,90' },
    { image: '/lovable-uploads/galeria/R$14,90 .jpeg', price: 'R$ 14,90' },
    { image: '/lovable-uploads/galeria/R$14,90.jpeg', price: 'R$ 14,90' },
    { image: '/lovable-uploads/galeria/R$15,90  .png', price: 'R$ 15,90' },
    { image: '/lovable-uploads/galeria/R$15,90 .jpeg', price: 'R$ 15,90' },
    { image: '/lovable-uploads/galeria/R$15,90.jpeg', price: 'R$ 15,90' },
    { image: '/lovable-uploads/galeria/R$16,50.jpeg', price: 'R$ 16,50' },
    { image: '/lovable-uploads/galeria/R$16,90.jpeg', price: 'R$ 16,90' },
    { image: '/lovable-uploads/galeria/R$16,90.png', price: 'R$ 16,90' },
    { image: '/lovable-uploads/galeria/R$17,50.jpeg', price: 'R$ 17,50' },
    { image: '/lovable-uploads/galeria/R$17,50.png', price: 'R$ 17,50' },
    { image: '/lovable-uploads/galeria/R$18,90 .jpeg', price: 'R$ 18,90' },
    { image: '/lovable-uploads/galeria/R$18,90.jpeg', price: 'R$ 18,90' },
    { image: '/lovable-uploads/galeria/R$19,90   .jpeg', price: 'R$ 19,90' },
    { image: '/lovable-uploads/galeria/R$19,90  .jpeg', price: 'R$ 19,90' },
    { image: '/lovable-uploads/galeria/R$19,90.jpeg', price: 'R$ 19,90' },
    { image: '/lovable-uploads/galeria/R$19,90.png', price: 'R$ 19,90' },
    { image: '/lovable-uploads/galeria/R$20,90.jpeg', price: 'R$ 20,90' },
    { image: '/lovable-uploads/galeria/R$21,90  .jpeg', price: 'R$ 21,90' },
    { image: '/lovable-uploads/galeria/R$21,90 .jpeg', price: 'R$ 21,90' },
    { image: '/lovable-uploads/galeria/R$21,90.jpeg', price: 'R$ 21,90' },
    { image: '/lovable-uploads/galeria/R$22,50  .jpeg', price: 'R$ 22,50' },
    { image: '/lovable-uploads/galeria/R$22,50 .jpeg', price: 'R$ 22,50' },
    { image: '/lovable-uploads/galeria/R$22,50.jpeg', price: 'R$ 22,50' },
    { image: '/lovable-uploads/galeria/R$23,50.jpeg', price: 'R$ 23,50' },
    { image: '/lovable-uploads/galeria/R$24,50 .jpeg', price: 'R$ 24,50' },
    { image: '/lovable-uploads/galeria/R$24,50.jpeg', price: 'R$ 24,50' },
    { image: '/lovable-uploads/galeria/R$25,90.jpeg', price: 'R$ 25,90' },
    { image: '/lovable-uploads/galeria/R$26,50.jpeg', price: 'R$ 26,50' },
    { image: '/lovable-uploads/galeria/R$26,90.png', price: 'R$ 26,90' },
    { image: '/lovable-uploads/galeria/R$27,90 .jpeg', price: 'R$ 27,90' },
    { image: '/lovable-uploads/galeria/R$27,90.jpeg', price: 'R$ 27,90' },
    { image: '/lovable-uploads/galeria/R$28,50.jpeg', price: 'R$ 28,50' },
    { image: '/lovable-uploads/galeria/R$29,90 .jpeg', price: 'R$ 29,90' },
    { image: '/lovable-uploads/galeria/R$29,90 .png', price: 'R$ 29,90' },
    { image: '/lovable-uploads/galeria/R$29,90.jpeg', price: 'R$ 29,90' },
    { image: '/lovable-uploads/galeria/R$3,50.jpeg', price: 'R$ 3,50' },
    { image: '/lovable-uploads/galeria/R$3,90.jpeg', price: 'R$ 3,90' },
    { image: '/lovable-uploads/galeria/R$32,50 .jpeg', price: 'R$ 32,50' },
    { image: '/lovable-uploads/galeria/R$32,50.png', price: 'R$ 32,50' },
    { image: '/lovable-uploads/galeria/R$32,90.jpeg', price: 'R$ 32,90' },
    { image: '/lovable-uploads/galeria/R$34,90.jpeg', price: 'R$ 34,90' },
    { image: '/lovable-uploads/galeria/R$35,0.jpeg', price: 'R$ 35,00' },
    { image: '/lovable-uploads/galeria/R$36,90.png', price: 'R$ 36,90' },
    { image: '/lovable-uploads/galeria/R$39,90  .jpeg', price: 'R$ 39,90' },
    { image: '/lovable-uploads/galeria/R$39,90  .png', price: 'R$ 39,90' },
    { image: '/lovable-uploads/galeria/R$39,90 .jpeg', price: 'R$ 39,90' },
    { image: '/lovable-uploads/galeria/R$39,90.jpeg', price: 'R$ 39,90' },
    { image: '/lovable-uploads/galeria/R$39,90.png', price: 'R$ 39,90' },
    { image: '/lovable-uploads/galeria/R$5,90.jpeg', price: 'R$ 5,90' },
    { image: '/lovable-uploads/galeria/R$59,90.jpeg', price: 'R$ 59,90' },
    { image: '/lovable-uploads/galeria/R$6,80 .jpeg', price: 'R$ 6,80' },
    { image: '/lovable-uploads/galeria/R$6,80.jpeg', price: 'R$ 6,80' },
    { image: '/lovable-uploads/galeria/R$7,50.jpeg', price: 'R$ 7,50' },
    { image: '/lovable-uploads/galeria/R$7,50.png', price: 'R$ 7,50' },
    { image: '/lovable-uploads/galeria/R$8,50.jpeg', price: 'R$ 8,50' },
    { image: '/lovable-uploads/galeria/R$8,90 .jpeg', price: 'R$ 8,90' },
    { image: '/lovable-uploads/galeria/R$8,90.jpeg', price: 'R$ 8,90' }
  ];

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Search and Filter Section */}
      <
